- hosts: all
  tasks:
  - name: deploy a simple template file
    ansible.builtin.copy:
      src: /tmp/tst_copy.txt
      dest: /tmp/tst_copy.txt
      owner: diego
      group: diego
      mode: '0755'
