- hosts: all
  tasks:
  - name: deploy a simple template file
    ansible.builtin.copy:
      src: /shared/tst_copy.txt
      dest: /tmp/tst_copy.txt
      owner: awx
      group: awx
      mode: '0755'
    
    
