---
- name: simple playbook
  hosts: all
  become: yes
  tasks:
#  - name: install vsftpd
#    yum: name=vsftpd
#  - name: enable vsftpd
#    service: name=vsftpd enabled=true
  - name: create readme file
    copy:
      content: "welcome to my ftp server"
      dest: /tmp/README
      force: no
      mode: 0444
...
